########################################
#                                      #
#             Xeow Config              #
#                                      #
########################################

Token: ""
Prefix: "-"
SlashCommand: true
PrefixCommand: true
Lang: en


########################################
#                                      #
#               DATABASE               #
#                                      #
########################################

Storage:
    Type: "sqlite"

    MySQL:
        Host: ""
        Port: ""
        Database: ""
        User: ""
        Password: ""


########################################
#                                      #
#                Logger                #
#                                      #
########################################
Logger:
  debug: false
  lang: "zh-tw"
  format: "LL LTS"

########################################
#                                      #
#            Advance Config            #
#                                      #
########################################

BotVersion: "1.0.0"