########################################
#                                      #
#           Xeow Bot Config            #
#                                      #
########################################

Token: ""
Prefix: "+"
SlashCommand: true
PrefixCommand: true
Lang: en-US
SupportedLang: ["zh-TW", "zh-CN"]
ownerId: "000000000000000000"
Activities:
 - name: "+help"
Status: "online"
checkForUpdate: true


########################################
#                                      #
#               DATABASE               #
#                                      #
########################################

Storage:
    Type: "sqlite"

    MySQL:
        Host: ""
        Port: ""
        Database: ""
        Username: ""
        Password: ""


########################################
#                                      #
#                Logger                #
#                                      #
########################################
Logger:
  debug: false
  locale: "en-US"
  ignore: []
  momentFormat: "LL LTS"

########################################
#                                      #
#            Advance Config            #
#                                      #
########################################

BotVersion: "1.0.0"