########################################
#                                      #
#             Xeow Config              #
#                                      #
########################################

Token: ""
Prefix: "+"
SlashCommand: true
PrefixCommand: true
Lang: zh-TW


########################################
#                                      #
#               DATABASE               #
#                                      #
########################################

Storage:
    Type: "sqlite"

    MySQL:
        Host: ""
        Port: ""
        Database: ""
        Username: ""
        Password: ""


########################################
#                                      #
#                Logger                #
#                                      #
########################################
Logger:
  debug: false
  locale: "zh-tw"
  ignore: []
  momentFormat: "LL LTS"

########################################
#                                      #
#            Advance Config            #
#                                      #
########################################

BotVersion: "1.0.0"