########################################
#                                      #
#             Xeow Config              #
#                                      #
########################################

Token: ""
Prefix: "+"
SlashCommand: 
  enabled: true
  autoDeployOnStart: false
PrefixCommand: true
Lang: zh-tw


########################################
#                                      #
#               DATABASE               #
#                                      #
########################################

Storage:
    Type: "sqlite"

    MySQL:
        Host: ""
        Port: ""
        Database: ""
        Username: ""
        Password: ""


########################################
#                                      #
#                Logger                #
#                                      #
########################################
Logger:
  debug: false
  lang: "zh-tw"
  ignore: []

########################################
#                                      #
#            Advance Config            #
#                                      #
########################################

BotVersion: "1.0.0"